format = """
[](#59c2ff)\
$username\
[](bg:#ff8f40 fg:#59c2ff)\
$directory\
[](fg:#ff8f40 bg:#95e6cb)\
$nodejs\
$rust\
$lua\
$python\
[](fg:#95e6cb bg:#aad94c)\
$time\
[](fg:#aad94c bg:#f07178)\
$status\
[ ](fg:#f07178)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#0d1017 bg:#59c2ff"
style_root = "fg:#0d1017 bg:#59c2ff"
format = '[$user ]($style)'

[directory]
style = "fg:#0d1017 bg:#ff8f40"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[status]
symbol = "ﮏ "
not_executable_symbol = ""
not_found_symbol = ""
style = "fg:#0d1017 bg:#f07178"
format = '[[ $symbol ](fg:#0d1017 bg:#f07178)]($style)'
disabled = false

[nodejs]
symbol = " "
style = "fg:#0d1017 bg:#95e6cb"
format = '[[ $symbol ($version) ](fg:#0d1017 bg:#95e6cb)]($style)'

[rust]
symbol = " "
style = "fg:#0d1017 bg:#95e6cb"
format = '[[ $symbol ($version) ](fg:#0d1017 bg:#95e6cb)]($style)'

[python]
symbol = "  "
style = "fg:#0d1017 bg:#95e6cb"
format = '[[ $symbol ($version) ](fg:#0d1017 bg:#95e6cb)]($style)'

[lua]
symbol = " "
style = "fg:#0d1017 bg:#95e6cb"
format = '[[ $symbol ($version) ](fg:#0d1017 bg:#95e6cb)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#0d1017 bg:#aad94c"
format = '[[   $time ](fg:#0d1017 bg:#aad94c)]($style)'
