[colors]
ansi = [
  '#313244',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#89dceb',
  '#a6adc8',
]
brights = [
  "#45475a",
  "#f38ba8",
  "#a6e3a1",
  "#f9e2af",
  "#89b4fa",
  "#f5c2e7",
  "#89dceb",
  "#bac2de",
]

background = '#1e1e2e'
foreground = '#cdd6f4'
cursor_bg = '#cdd6f4'
cursor_fg = '#313244'
cursor_border = '#313244'
selection_fg = '#1e1e2e'
selection_bg = '#89dceb'
scrollbar_thumb = '#313244'
split = '#1e1e2e'

[colors.indexed]

[metadata]
name = 'Catppuccin Mocha'
