[colors]
ansi = [
  '#303446',
  '#e78284',
  '#a6d189',
  '#e5c890',
  '#8caaee',
  '#f4b8e4',
  '#99d1db',
  '#c6d0f5',
]
brights = [
  "#414559",
  "#e78284",
  "#a6d189",
  "#e5c890",
  "#8caaee",
  "#f4b8e4",
  "#99d1db",
  "#b5bfe2",
]

background = '#303446'
foreground = '#c6d0f5'
cursor_bg = '#c6d0f5'
cursor_fg = '#c6d0f5'
cursor_border = '#c6d0f5'
selection_fg = '#303446'
selection_bg = '#99d1db'
scrollbar_thumb = '#c6d0f5'
split = '#303446'

[colors.indexed]

[metadata]
name = 'Catppuccin Frappe'
