[colors]
ansi = [
  '#1e1e2e',
  '#f38ba8',
  '#a6e3a1',
  '#f9e2af',
  '#89b4fa',
  '#f5c2e7',
  '#89dceb',
  '#bac2de',
]
brights = [
  "#313244",
  "#f38ba8",
  "#a6e3a1",
  "#f9e2af",
  "#89b4fa",
  "#f5c2e7",
  "#89dceb",
  "#cdd6f4",
]

background = '#1e1e2e'
foreground = '#cdd6f4'
cursor_bg = '#cdd6f4'
cursor_fg = '#cdd6f4'
cursor_border = '#cdd6f4'
selection_fg = '#1e1e2e'
selection_bg = '#89dceb'
scrollbar_thumb = '#cdd6f4'
split = '#1e1e2e'

[colors.indexed]

[metadata]
name = 'Catppuccin Mocha'
