[colors]
ansi = [
  '#1c252c',
  '#e05f65',
  '#78dba9',
  '#f1cf8a',
  '#70a5eb',
  '#c68aee',
  '#74bee9',
  '#dee1e6',
]
brights = [
  "#384148",
  "#fc7b81",
  "#94f7c5",
  "#ffeba6",
  "#8cc1ff",
  "#e2a6ff",
  "#90daff",
  "#fafdff",
]

background = '#101419'
foreground = '#b6beca'
cursor_bg = '#dee1e6'
cursor_fg = '#22262e'
cursor_border = '#fafdff'
selection_fg = '#D9E0EE'
selection_bg = '#575268'
scrollbar_thumb = '#384148'
split = '#22262e'

[colors.indexed]

[metadata]
name = 'Decay'
